name:                stockell
version:             0.1.0.0
github:              "Francososa/stockell"
license:             BSD3
author:              "Francisco Sosa"
maintainer:          "franky.sosa@gmail.com"
copyright:           "Copyright (c) 2019 Francisco Sosa"

extra-source-files:
- README.md
- ChangeLog.md

description: Please see the README on GitHub at <https://github.com/Francososa/stockell#readme>

dependencies:
- base >= 4.10 && <4.13
- bytestring >=0.10 && <0.11
- blaze-html >=0.9 && <0.10
- optparse-applicative >=0.14 && <0.15
- time >=1.8 && <1.10
- text >=1.2 && <1.3
- fmt >=0.5 && <0.7
- safe >=0.3 && <0.4
- Chart >=1.8 && <1.10
- Chart-diagrams >=1.8 && <1.10
- cassava >=0.5 && <0.6

library:
  source-dirs: src

executables:
  stockell-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - stockell

tests:
  stockell-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - stockell
